services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tutorra}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tutorra}
      POSTGRES_DB: ${POSTGRES_DB:-tutorra}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    # command will be added in Module 3+

  runner:
    build:
      context: ./runner
    env_file:
      - ./api/.env
    depends_on:
      - api
    # resource limits enforced inside Dockerfile in Module 8

  web:
    build:
      context: ./web
    env_file:
      - ./web/.env.local
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
